# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4e8b6b4ad166562d5b520143f8572e2710a361c1ac6dc89579c4b994b6de67e34775a5b102d1015ab485983383e3ed78dd644aaa5c5fb90a3f4057ef12db1f2

test:
  secret_key_base: 55b3639c1fa8a0476b5cfc9e5b78cb7f47518bf01765e265615857da9961ada3b9c81e76850dd660521971f4c02ff5e8ac360707d5674e35dfb87a0d793d9cca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
